### ISSUE TITLE
検討希望: モジュールバンドラの利用

### ISSUE THREAD

**Issue by c6h4clch3** [Minori-Akizuki/ddntj#16]
フロントエンドで利用するJavaScriptファイルについて、
現状の機能のみでしたら数ファイルで十分かと思いますが、
現在Issueとして上がっているような機能や
どどんとふで実装されているような機能をこちらでも実装しようと考えた際、
開発規模が膨れ上がることが想定されます。

Webpack/Browserifyなど、
モジュールバンドラで複数のJSファイルを結合したものを読み込むのはどうでしょうか。

**Comment by Minori-Akizuki** [comment]
Webpackどう使えばいいのかいま必死に勉強しています……
一回使った時にVueをモジュール化した時の設定がうまくいかなくて挫折したんですよね…
ちょっと切り分けからちゃんとやってみますか…

**Comment by c6h4clch3** [comment]
一応ざっとWebpack利用とVueコンポーネント化適用でリファクタリングしました。
少々強引だったりコミットログ汚れてたりですが何かご参考になれば。
https://github.com/c6h4clch3/ddntj/tree/develop

**Comment by Minori-Akizuki** [comment]
おぉぉありがとうございます……!
この辺私もちゃんと読みこまないとワケワカメになるので
ちょっと理解するのにお時間ください…

**Comment by Minori-Akizuki** [comment]
理解追いついていないところもありますが大体読みました…なるほど……
少しずつ取り込んで行きたいと思います。あるいはプルリクいただけるのであればdeveropにとりこまさせて頂きたいです!
(人のforkを横取りする方法を知らない……)
よろしくおねがいします!

**Comment by c6h4clch3** [comment]
一応プルリク出しました。

ちょっとNode.jsの知識が薄いんでバックエンドはかなり強引なことやってるんじゃないかなと思いますが、フロントはうまくコンポーネント化できたかなと思ってます。
