### ISSUE TITLE
機能追加 : キャラステータス管理

### ISSUE THREAD

**Issue by Minori-Akizuki** [Minori-Akizuki/ddntj#2]
キャラの一覧からステータス管理したい

**Comment by Shunshun94** [comment]
[https://github.com/Shunshun94/manaT](キャラクターステータス管理用アプリ) を書いてみました。
こいつで楽にやれないかな？って思ってます

**Comment by c6h4clch3** [comment]
@Shunshun94 ソースコード拝見しました。
データ構造自体をとふのものとそろえるという方針、いいと思います。

クライアント側のストアオブジェクトでしたらVuexというVue公式のストアライブラリがあるので、
まなてぃをVuexから利用できるラッパーを書けばいい感じかもですね。
サーバ側のストアにするにはNodeプロセスが落ちたら失われてしまうので
ファイル出力かDB保存かでデータを永続化するのが今後の課題でしょうか？

**Comment by Shunshun94** [comment]
クライアントに組み込んでしまう、という発想はありませんでした。
その方が管理するものは減って楽な気はしますね……

サーバサイドとしてはファイル出力や DB 保存は早めにやりたいところです。
(使うミドルウェアが増えないファイル出力が最初にくると思っています)

**Comment by c6h4clch3** [comment]
環境変数の有無でミドルウェアの有無を切り替える形
(MongoDBの接続URLなど)でもいいかもですね＞サーバサイド

・フロントサイド: Vuexについて
VuexはVueアプリケーション内の全てのコンポーネント内で
共有できるオブジェクトストアです。
(その分保存の仕方などは制約がつきます)

Vueは親から子への単方向データバインディングなので
子の変更を親に伝えるのは骨が折れますが共有ストアを利用することで
複雑なデータフローがスッキリできます。
各種サブウィンドウ・マップ・サイドバーなどで
キャラクターやチャット設定など使い回す部分が多いので
この仕組みは使って損はないと思います。
