### ISSUE TITLE
機能追加 : ファイルアップロード

### ISSUE THREAD

**Issue by Minori-Akizuki** [Minori-Akizuki/ddntj#20]
これがないと始まらないっすね。
コマとかマップとかに使用する画像をアップロードできるようにしたい。
挿絵とかムービーとかだったら動画もアリアリ。

これDB使った方がいいんですかね。それともさしあたっての実装でふつーにファイルで保存しておけばいいですかね。

**Comment by Minori-Akizuki** [comment]
どどんとふにならってタグぐらいつけられるようにしないと多分画像の管理が大変な事になるのでつけられるようにしましょう。

**Comment by c6h4clch3** [comment]
Node.jsの時点でレンタルサーバよりはVPSでの利用ケースが多いかなと思うんですが、
そうすると個人的にはDB利用はミドルウェアが増えるのが心配かなと思います。
(ユーザが利用したいときにミドルウェアをインストールする必要がある=
 利用できるまでのハードルが上がる)

でもファイル保存だとタグのつけ方考える必要ありますよね...悩ましい

**Comment by c6h4clch3** [comment]
HerokuなどのPaaSだとミドルウェアをサービス側でごにょごにょしてくれるので、
それらで一発で動かせるように設定ファイル書くのも視野に入れてみてもいいかもしれません。

**Comment by Minori-Akizuki** [comment]
NoSQLとかだったらタグ付けも簡単だった気がするんですがふつーのDBだとそれはそれでむずかしそうですね…どのみち万は行かないだろうしファイル管理でいいかな……サムネとか一緒に保存しなきゃいけないし。

**Comment by c6h4clch3** [comment]
NoSQLで自分が知識あるmongoDBとかだと画像(できればその他のファイルも)のPathと(部屋番号と)タグのリストを持ったドキュメントのコレクション作ればいいかなー、って感じですね。
mongoはドキュメントの容量増やしたくないので必然的にアップロードされたファイルの実体は普通に保存してパスをドキュメントで管理する形になりそうです。
鯖缶はファイルの実体だけでなくmongoのドキュメントも掃除しなくちゃならないですが。

ファイル管理にしてもサーバ止まったら画像消えてましたじゃ洒落にならないので、部屋別の設定ファイルへの書き出しなどの永続化が必要そうな感じします。

**Comment by Minori-Akizuki** [comment]
あまり部屋別に管理する気はないですけどねー。なんとなくですけどこんな情報どっかに保存しておけばいいかなと

* サーバ上ハッシュ名
* [タグ……]
* 動画/静止画の別

マップ上のキャラ情報は何処かに永続保存したいですがそれはマップ機能の範疇かな…
