### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by daicyan** [Minori-Akizuki/ddntj#4]
どどんとふ公式鯖管理人です。
早速試してみましたが、package.jsonに、log4jsとjqueryがないためにnpm startしてもエラーになってしまいました。
とりあえず、手動でこの2つをnpm installで入れたら動きましたので、package.jsonに追加していただけますでしょうか？

**Comment by Minori-Akizuki** [comment]
早速試していただいてありがとうございます！
インストールの時に --save してなかったやつですね……
修正いたしました！
